const bank=[
 {a:"Código RAN",alt:["RAN","Código RAN de heridas"],q:"¿Qué código de valoración de heridas soy?",c:["Mi nombre se forma con las iniciales de tres colores.","Clasifico el lecho de la herida según el tejido presente.","El amarillo indica exudado o fibrina y el negro, necrosis.","Uso rojo, amarillo y negro para orientar los objetivos de la cura."],e:"El código RAN clasifica las heridas por el color del tejido del lecho: rojo, amarillo y negro."},
 {a:"EVE",alt:["Escala Visual del Eritema","Escala Visual del Eritema EVE"],q:"¿Qué escala cutánea soy?",c:["Valoro una manifestación frecuente en lesiones por humedad.","Mi rango va de 0 a 4.","El valor 0 significa ausencia y el 3, intensidad elevada.","Mi nombre completo es Escala Visual del Eritema."],e:"La EVE gradúa el eritema de 0 (no eritema) a 4 (piel rota o abrasión superficial)."},
 {a:"Braden",alt:["Escala de Braden"],q:"¿Qué escala de riesgo soy?",c:["Soy una escala de tipo negativo.","Incluyo seis dimensiones y una de ellas se puntúa de 1 a 3.","Valoro percepción sensorial, humedad, actividad, movilidad y nutrición.","Mi intervalo total es de 6 a 23 puntos y añado fricción/cizallamiento."],e:"Braden valora seis factores. A menor puntuación, mayor riesgo de lesión por presión."},
 {a:"Norton",alt:["Escala de Norton","Norton modificada"],q:"¿Qué escala de riesgo soy?",c:["Fui creada en 1962 y posteriormente modificada.","Soy una escala de tipo negativo con cinco parámetros.","Valoro estado físico, estado mental, actividad, movilidad e incontinencia.","Mi puntuación oscila entre 5 y 20 puntos."],e:"Norton evalúa cinco parámetros; a menor puntuación, mayor riesgo de LPP."},
 {a:"EMINA",alt:["Escala EMINA"],q:"¿Qué escala de riesgo soy?",c:["Fui elaborada por un grupo de Enfermería del Institut Català de la Salut.","Mi puntuación aumenta conforme aumenta el riesgo.","Mis cinco parámetros se puntúan de 0 a 3.","Mi nombre resume Estado mental, Movilidad, Incontinencia-humedad, Nutrición y Actividad."],e:"EMINA es una escala positiva de 0 a 15: una puntuación mayor indica mayor riesgo."},
 {a:"e-PAT",alt:["EPAT","Perineal Risk Assessment Tool","Perineal Assessment Tool"],q:"¿Qué herramienta de valoración soy?",c:["Me centro en un problema cutáneo vinculado a la incontinencia.","Valoro cuatro apartados, cada uno de 1 a 3.","Incluyo intensidad y duración del irritante, condición de la piel y factores contribuyentes.","Por encima de 7 puntos indico riesgo alto de dermatitis asociada a incontinencia."],e:"e-PAT valora el riesgo de dermatitis asociada a la incontinencia mediante cuatro dimensiones."},
 {a:"Edmonds",alt:["Escala de Edmonds","Clasificación de Edmonds"],q:"¿Qué clasificación clínica soy?",c:["Me aplico al pie diabético.","Ayudo a distinguir dos tipos de úlcera.","Una de ellas suele ser indolora y presentar pulsos; la otra, dolorosa y sin pulsos.","Diferencio la úlcera neuropática de la neuroisquémica."],e:"Edmonds orienta el diagnóstico diferencial entre úlcera neuropática y neuroisquémica."},
 {a:"Fedpalla",alt:["Escala Fedpalla"],q:"¿Qué escala relacionada con heridas soy?",c:["Observo de forma específica dos elementos anatómicos de la lesión.","También ayudo a anticipar la evolución de la cicatrización.","Valoro los bordes de la herida y el estado de la piel perilesional.","Mi nombre comienza por «Fed»."],e:"Fedpalla valora bordes y piel perilesional y establece un pronóstico de cicatrización."},
 {a:"Braden Q",alt:["Escala Braden Q","BradenQ"],q:"¿Qué adaptación pediátrica soy?",c:["Procedo de una escala empleada también en adultos.","Mantengo seis factores de mi escala de origen.","Adapto definiciones a la población pediátrica y añado un séptimo factor.","Ese factor añadido es oxigenación y perfusión tisular."],e:"Braden Q adapta Braden a pediatría y añade oxigenación/perfusión tisular."},
 {a:"Glasgow del melanoma",alt:["Escala de Glasgow","Glasgow","7 puntos de Glasgow"],q:"¿Qué sistema diagnóstico dermatológico soy?",c:["No valoro el nivel de conciencia.","Reúno tres criterios mayores y cuatro menores.","Mis criterios mayores son cambios de tamaño, forma y color.","Con 3 o más puntos una lesión es sospechosa de melanoma."],e:"El sistema de 7 puntos de Glasgow orienta la sospecha diagnóstica de melanoma."},
 {a:"Regla de Wallace",alt:["Wallace","Regla de los 9","Regla de Wallace o de los 9"],q:"¿Qué método para quemaduras soy?",c:["Estimo extensión, no profundidad.","Divido regiones corporales en porcentajes fáciles de recordar.","En el adulto, cabeza y cada brazo representan un 9 %.","También me conocen como regla de los 9."],e:"La regla de Wallace estima la superficie corporal quemada mediante múltiplos de nueve."},
 {a:"Lund-Browder",alt:["Lund Browder","Tabla de Lund-Browder","Lund y Browder"],q:"¿Qué método para quemaduras soy?",c:["Estimo la extensión de una quemadura.","Soy más detallado que una regla basada en múltiplos fijos.","Ajusto los porcentajes de las regiones corporales.","Tengo en cuenta la edad del paciente."],e:"Lund-Browder estima la extensión de la quemadura adaptando las proporciones corporales a la edad."},
 {a:"Score de Baux",alt:["Baux","Índice de Baux"],q:"¿Qué índice pronóstico soy?",c:["Me empleo en pacientes quemados.","Relaciono dos datos clínicos sencillos.","Estimo probabilidad de mortalidad.","Sumo el porcentaje de superficie corporal quemada y la edad."],e:"El score de Baux clásico suma %SCQ y edad; el modificado incorpora 17 puntos adicionales según el material aportado."},
 {a:"Fórmula de Parkland",alt:["Parkland"],q:"¿Qué fórmula de reposición soy?",c:["Calculo volumen para las primeras 24 horas.","Uso peso corporal y porcentaje de superficie corporal quemada.","Administro la mitad del volumen calculado durante las primeras 8 horas.","Mi expresión es 4 ml × kg × %SCQ."],e:"Parkland calcula el volumen inicial con 4 ml × peso (kg) × %SCQ; la mitad se administra en las primeras 8 horas."},
 {a:"Brooke modificada",alt:["Fórmula de Brooke modificada","Brooke"],q:"¿Qué fórmula de reposición soy?",c:["Soy una alternativa para pacientes quemados.","Mantengo la misma distribución temporal que otra fórmula conocida.","Propongo menor cantidad de cristaloide.","Utilizo 2 ml/kg por porcentaje de superficie corporal quemada."],e:"Brooke modificada emplea 2 ml/kg/%SCQ, con 50 % en las primeras 8 horas y el resto en las 16 siguientes."}
];
let deck=[],idx=0,score=0,lives=3,hints=0,correct=0,locked=false,current=null,shown=1;
const $=id=>document.getElementById(id); const norm=s=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/g,"");
function shuffle(a){for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function startGame(){let recent=[];try{recent=JSON.parse(localStorage.getItem("opolab_recent")||"[]")}catch(e){} let fresh=bank.filter(x=>!recent.includes(x.a)); deck=shuffle(fresh).concat(shuffle(bank.filter(x=>recent.includes(x.a)))).slice(0,10); idx=score=hints=correct=0;lives=3;$("start").classList.add("hidden");$("result").classList.add("hidden");$("game").classList.remove("hidden");load()}
function load(){locked=false;shown=1;current=deck[idx];let cs=[...current.c]; if(Math.random()>.5&&cs.length>3)[cs[1],cs[2]]=[cs[2],cs[1]];current.playClues=cs;$("round").textContent=(idx+1)+" / "+deck.length;$("score").textContent=score.toLocaleString("es-ES");$("lives").textContent="♥ ".repeat(lives).trim();$("bar").style.width=((idx+1)/deck.length*100)+"%";$("caseid").textContent="EXPEDIENTE "+String(idx+1).padStart(2,"0");$("question").textContent=current.q;$("answer").value="";$("answer").disabled=false;$("check").disabled=false;$("feedback").className="feedback hidden";$("next").classList.add("hidden");$("hint").classList.remove("hidden");renderClues();$("answer").focus();updateBest()}
function renderClues(){$("clues").innerHTML=current.playClues.slice(0,shown).map((x,i)=>'<div class="clue"><b>PISTA '+(i+1)+'</b>'+x+'</div>').join("");$("value").textContent=(1000-(shown-1)*200).toLocaleString("es-ES")+" puntos";if(shown>=current.playClues.length)$("hint").classList.add("hidden")}
function reveal(){if(locked)return;if(shown<current.playClues.length){shown++;hints++;renderClues()}}
function finish(ok){locked=true;$("answer").disabled=true;$("check").disabled=true;$("hint").classList.add("hidden");let pts=1000-(shown-1)*200;if(ok){score+=pts;correct++;$("feedback").className="feedback good";$("feedback").innerHTML="<strong>✓ Caso resuelto · +"+pts.toLocaleString("es-ES")+" puntos</strong>"+current.e}else{$("feedback").className="feedback bad";$("feedback").innerHTML="<strong>La respuesta era: "+current.a+"</strong>"+current.e}$("score").textContent=score.toLocaleString("es-ES");$("next").classList.remove("hidden");$("next").textContent=idx===deck.length-1||lives===0?"Ver resultado":"Siguiente expediente →"}
function submit(e){e.preventDefault();if(locked)return;let v=norm($("answer").value);if(!v)return $("answer").focus();let ok=[current.a,...current.alt].some(x=>norm(x)===v);if(ok)finish(true);else{lives--;$("lives").textContent="♥ ".repeat(lives).trim()||"—";finish(false)}}
function goNext(){if(idx<deck.length-1&&lives>0){idx++;load()}else end()}
function end(){let best=Math.max(score,Number(localStorage.getItem("opolab_best")||0));localStorage.setItem("opolab_best",best);localStorage.setItem("opolab_recent",JSON.stringify(deck.map(x=>x.a)));$("game").classList.add("hidden");$("result").classList.remove("hidden");$("finalScore").textContent=score.toLocaleString("es-ES");$("hits").textContent=correct;$("used").textContent=hints;$("resultTitle").textContent=correct>=8?"¡Diagnóstico brillante!":correct>=5?"¡Buen trabajo de investigación!":"Hay pistas que conviene revisar";$("resultText").textContent="Has resuelto "+correct+" de "+(idx+1)+" expedientes. Tu mejor marca en este dispositivo es "+best.toLocaleString("es-ES")+" puntos."}
function updateBest(){let b=Number(localStorage.getItem("opolab_best")||0);$("best").textContent=b?b.toLocaleString("es-ES")+" pts":"Primera partida"}
$("startGameButton").addEventListener("click",startGame);$("replayButton").addEventListener("click",startGame);$("hint").addEventListener("click",reveal);$("form").addEventListener("submit",submit);$("next").addEventListener("click",goNext);updateBest();
